CREATE TABLE IF NOT EXISTS persistent_logins (
	username VARCHAR(64) NOT NULL, 
	series VARCHAR(64) PRIMARY KEY, 	
	token VARCHAR(64) NOT NULL,
	last_used TIMESTAMP NOT NULL
);
INSERT INTO user_role(role, description) VALUES ("ROLE_USER", "default role for user");
INSERT INTO user_role(role, description) VALUES ("ROLE_ADMIN", "administrator");
INSERT INTO user(email, first_name, last_name, password) VALUES ("latidude99test@gmail.com", "Lati", "Dude", "1100011");
INSERT INTO user(email, first_name, last_name, password) VALUES ("test@test.com", "test", "test", "111111");
INSERT INTO user(email, first_name, last_name, password) VALUES ("demo@demo.com", "demo", "demo", "111111");

INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-01 18:50:22", "Urzednicza 12", "31-125","Krakow", "Poland", "administrator test contact", "endel@gmail.com", "Anna", "Borowska", "601903774", "1");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-02 18:50:22", "Brzozowa 34", "30-145","Warszawa", "Poland", "administrator test contact", "erew22@btinternet.com", "Maciej", "Rudy", "6692665112", "1");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-03 18:50:22", "Grzybowa 52", "30-145","Poznan", "Poland", "administrator test contact", "erty54@yahoo.com", "Tomasz", "Piniew", "6064890233", "1");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-04 18:50:22", "Krolewska 2", "30-145","Gdansk", "Poland", "administrator test contact", "gfdg66@gmail.com", "Jan", "Grom", "669589477", "1");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-05 18:50:22", "Rodzaj 66a", "30-145","Wroclaw", "Poland", "administrator test contact", "jhgfds@hotmail.com", "Linda", "Krolitova", "533690458", "1");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-06 18:50:22", "Krzaki 11", "30-145","Pcim Dolny", "Poland", "userDemo test contact", "kjhgfd@nutella.pl", "Zdzislaw", "Morda", "601349778", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-07 18:50:22", "Wyraz 8B m43", "30-145","Zadupie Gorne", "Poland", "userDemo test contact", "mnbvc@onet.pl", "Stefan", "Szczegolny", "612684580", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-08 18:50:22", "Stolikowa 10", "30-145","Wygwizdow", "Poland", "userDemo test contact", "rewq6@onet.pl", "Grazyna", "Sadelko", "533689326", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-09 18:50:22", "Suma 5C/12", "30-145","Wolka Czarna", "Poland", "userDemo test contact", "tghgtr@wp.pl", "Dzesika", "Blacha", "60861405", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-10 18:50:22", "Zawias 3", "30-145","Pierdziszew", "Poland", "userDemo test contact", "rtyuir@owo.pl", "Sebastian", "Zyleta", "610689445", "2");

INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-11 18:50:22", "Station Rd,", "TN19 7PL","  Etchingham", "United Kingdom", "Romanian-Italian archaeologist, a pioneer and promoter of the use of aerial photography and aerial survey in archaeology", "latidude99@gmail.com", "Dinu", "Adameșteanu", "+445668867760", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-12 18:50:22", "Ahornweg 23", "98544","Zella-Mehlis", "Germany", "Italian-American physicist and the creator of the world's first nuclear reactor, the Chicago Pile-1. He has been called the architect of the nuclear age and the architect of the atomic bomb. He was one of the very few physicists in history to excel both theoretically and experimentally. Fermi held several patents related to the use of nuclear power, and was awarded the 1938 Nobel Prize in Physics for his work on induced radioactivity by neutron bombardment and the discovery of transuranic elements. He made significant contributions to the development of quantum theory, nuclear and particle physics, and statistical mechanics.", "fermi@gmail.com", "Enrico", "Fermi", "+567356767760", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-13 18:50:22", "Warszawska 14", "96-200","Rawa Mazowiecka", "Poland", "Planck made many contributions to theoretical physics, but his fame as a physicist rests primarily on his role as the originator of quantum theory, which revolutionized human understanding of atomic and subatomic processes. In 1948 the German scientific institution the Kaiser Wilhelm Society (of which Planck was twice president), was renamed the Max Planck Society (MPS). The MPS now includes 83 institutions representing a wide range of scientific directions.", "planck@hotmail.com", "Max", "Planck", "+488757797760", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-14 18:50:22", "Strada Victoriei 28", " ","Pitești", "Romania", "American novelist, short story writer, and journalist. His economical and understated style—which he termed the Iceberg Theory—had a strong influence on 20th-century fiction, while his adventurous lifestyle and his public image brought him admiration from later generations. Hemingway produced most of his work between the mid-1920s and the mid-1950s, and won the Nobel Prize in Literature in 1954. He published seven novels, six short-story collections, and two non-fiction works. Three of his novels, four short story collections, and three non-fiction works were published posthumously. Many of his works are considered classics of American literature", "ernest@hotmail.com", "Ernest", "Hemingway", "+4886787877760", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-15 18:50:22", "Ybl Miklós tér 2-6", "1013","Budapest", "Hungary", "Portuguese writer and recipient of the 1998 Nobel Prize in Literature. His works, some of which can be seen as allegories, commonly present subversive perspectives on historic events, emphasizing the theopoetic human factor. In 2003 Harold Bloom described Saramago as the most gifted novelist alive in the world today and in 2010 said he considers Saramago to be a permanent part of the Western canon, while James Wood praises the distinctive tone to his fiction because he narrates his novels as if he were someone both wise and ignorant", "jose.sara@gmail.com", "José ", "Saramago", "+4756575650", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-16 18:50:22", " Via Stella 22", "41121"," Modena", "Italy", "Polish poet, prose writer, translator and diplomat. His World War II-era sequence The World is a collection of twenty naïve poems. Following the war, he served as Polish cultural attaché in Paris and Washington, D.C., then in 1951 defected to the West. His nonfiction book The Captive Mind (1953) became a classic of anti-Stalinism. From 1961 to 1998 he was a professor of Slavic Languages and Literatures at the University of California, Berkeley. He became a U.S. citizen in 1970.[3] In 1978 he was awarded the Neustadt International Prize for Literature, and in 1980 the Nobel Prize in Literature. In 1999 he was named a Puterbaugh Fellow.[4] After the fall of the Iron Curtain, he divided his time between Berkeley, California, and Kraków, Poland.", "czesiek@gmail.com", "Czesław ", "Miłosz ", "+4568585657760", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-17 18:50:22", "51 bis avenue Georges Clemenceau", "34000","Montpellier", "France", "American author. He won the 1962 Nobel Prize in Literature for his realistic and imaginative writings, combining as they do sympathetic humour and keen social perception. He has been called a giant of American letters, and many of his works are considered classics of Western literature.", "john.s@gmail.com", "John", "Steinbeck", "+56577858585", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-18 18:50:22", "Norra Kustbanegatan 15", " 416 64","Göteborg", "Sweden", "American writer and Nobel Prize laureate from Oxford, Mississippi. Faulkner wrote novels, short stories, a play, poetry, essays, and screenplays. He is primarily known for his novels and short stories set in the fictional Yoknapatawpha County, based on Lafayette County, Mississippi, where he spent most of his life.", "faulkner@hotmail.com", "William", "Faulkner", "+458568566686", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-19 18:50:22", "Av. de la Institución Libre de Enseñanza, 190 bis", "28037","Madrid", "Spain", "British organic chemist[1] and Nobel laureate recognised in 1947 for his research on plant dyestuffs (anthocyanins) and alkaloids. In 1947, he also received the Medal of Freedom with Silver Palm.", "robinson @gmail.com", "Robert", "Robinson ", "+363645747777", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-20 18:50:22", " Casemates Square", "GX11 1AA","Gibraltar", "Gibraltar", "Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize, the first person and only woman to win twice, the only person to win a Nobel Prize in two different sciences, and was part of the Curie family legacy of five Nobel Prizes. She was also the first woman to become a professor at the University of Paris, and in 1995 became the first woman to be entombed on her own merits in the Panthéon in Paris.", " m.curie99@gmail.com", "Marie", " Skłodowska Curie", "+356868959899", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-21 18:50:22", "Av. da Liberdade 127", "1269-038","Lisboa", "Portugal", "Franco-Luxembourgish physicist and inventor, and Nobel laureate in physics for his method of reproducing colours photographically based on the phenomenon of interference.", "lippmann@hotmail.com", "Gabriel", "Lippmann", "+48679958989", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-22 18:50:22", "Cl. 49a #55a-40", " ","Medellín", "Colombia", "German chemist. He received the Nobel Prize in Chemistry in 1909 for his work on catalysis, chemical equilibria and reaction velocities. Ostwald, Jacobus Henricus van 't Hoff, Walther Nernst, and Svante Arrhenius are usually credited with being the modern founders of the field of physical chemistry.", "ostwald@gmail.com", "Wilhelm", "Ostwald", "+879786766657", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-23 18:50:22", "Av. Javier Prado Este 1212", "15036","Distrito de San Isidro", "Peru", "Scottish chemist who discovered the noble gases and received the Nobel Prize in Chemistry in 1904 in recognition of his services in the discovery of the inert gaseous elements in air (along with his collaborator, John William Strutt, 3rd Baron Rayleigh, who received the Nobel Prize in Physics that same year for their discovery of argon). After the two men identified argon, Ramsay investigated other atmospheric gases. His work in isolating argon, helium, neon, krypton and xenon led to the development of a new section of the periodic table.", "w.ramsay99@hotmail.com", "William", "Ramsay", "+412442343244", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-24 18:50:22", "Av. Pres. Vargas 1261 - Centro", "20071-004","Rio de Janeiro", "Brazil", "New Zealand-born British physicist who came to be known as the father of nuclear physics.[3] Encyclopædia Britannica considers him to be the greatest experimentalist since Michael Faraday (1791–1867)", "rutherford99@hotmail.com", "Ernest", "Rutherford", "+14343232343", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-25 18:50:22", "Balcarce 460", "C1064AAJ CABA,","Buenos Aires", "Argentina", "French poet, journalist, and successful novelist with several best-sellers. Ironic and skeptical, he was considered in his day the ideal French man of letters. He was a member of the Académie française, and won the 1921 Nobel Prize in Literature in recognition of his brilliant literary achievements, characterized as they are by a nobility of style, a profound human sympathy, grace, and a true Gallic temperament", "anatole1@gmail.com", "Anatole", "France", "+8907967699", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-26 18:50:22", "35-37 Essex St E", "D02 Y891","Dublin", "Ireland", "Danish professor at the department of zoophysiology at the University of Copenhagen from 1916 to 1945.[3][4][5] He contributed a number of fundamental discoveries within several fields of physiology, and is famous for developing the Krogh Principle", "august22@gmail.com", "August", "Krogh", "+35353633466", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-27 18:50:22", "18-22 Greenside Ln", "EH1 3AA","Edinburgh", "United Kingdom", "Slovenian and Austrian chemist and physician from a mixed Slovene-German-speaking background. He won the Nobel Prize in Chemistry in 1923 for making important contributions to quantitative organic microanalysis, one of which was the improvement of the combustion train technique for elemental analysis", "fritz.p@hotmail.com", "Fritz", "Pregl", "+5886786787667", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-28 18:50:22", "Northfield Ave", "NN16 8TP","Kettering", "United Kingdom", "Polish novelist and the 1924 laureate of the Nobel Prize in Literature. His best-known work is the award-winning four-volume novel Chłopi (The Peasants)", "w.reymont@gmail.com", "Władysław ", "Reymont", "+53453536466", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-29 18:50:22", "66 The Cut", "SE1 8LZ","London", "United Kingdom", "German theoretical physicist and one of the key pioneers of quantum mechanics. He published his work in 1925 in a breakthrough paper. In the subsequent series of papers with Max Born and Pascual Jordan, during the same year, this matrix formulation of quantum mechanics was substantially elaborated. He is known for the Heisenberg uncertainty principle, which he published in 1927. Heisenberg was awarded the 1932 Nobel Prize in Physics for the creation of quantum mechanics", "werner.h@hotmail.com", "Werner", "Heisenberg", "+676786338699", "2");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-30 18:50:22", " Mokhovaya St 6", "119019","Moskva", "Russia", "French philosopher, playwright, novelist, political activist, biographer, and literary critic. He was one of the key figures in the philosophy of existentialism and phenomenology, and one of the leading figures in 20th-century French philosophy and Marxism", "sartre.jp@gmail.com", "Jean-Paul", "Sartre", "+69978977064", "2");

INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-01 18:50:22", "Station Rd,", "TN19 7PL","  Etchingham", "United Kingdom", "Romanian-Italian archaeologist, a pioneer and promoter of the use of aerial photography and aerial survey in archaeology", "latidude99@gmail.com", "Dinu", "Adameșteanu", "+445668867760", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-02 18:50:22", "Ahornweg 23", "98544","Zella-Mehlis", "Germany", "Italian-American physicist and the creator of the world's first nuclear reactor, the Chicago Pile-1. He has been called the architect of the nuclear age and the architect of the atomic bomb. He was one of the very few physicists in history to excel both theoretically and experimentally. Fermi held several patents related to the use of nuclear power, and was awarded the 1938 Nobel Prize in Physics for his work on induced radioactivity by neutron bombardment and the discovery of transuranic elements. He made significant contributions to the development of quantum theory, nuclear and particle physics, and statistical mechanics.", "fermi@gmail.com", "Enrico", "Fermi", "+567356767760", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-03 18:50:22", "Warszawska 14", "96-200","Rawa Mazowiecka", "Poland", "Planck made many contributions to theoretical physics, but his fame as a physicist rests primarily on his role as the originator of quantum theory, which revolutionized human understanding of atomic and subatomic processes. In 1948 the German scientific institution the Kaiser Wilhelm Society (of which Planck was twice president), was renamed the Max Planck Society (MPS). The MPS now includes 83 institutions representing a wide range of scientific directions.", "planck@hotmail.com", "Max", "Planck", "+488757797760", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-04 18:50:22", "Strada Victoriei 28", " ","Pitești", "Romania", "American novelist, short story writer, and journalist. His economical and understated style—which he termed the Iceberg Theory—had a strong influence on 20th-century fiction, while his adventurous lifestyle and his public image brought him admiration from later generations. Hemingway produced most of his work between the mid-1920s and the mid-1950s, and won the Nobel Prize in Literature in 1954. He published seven novels, six short-story collections, and two non-fiction works. Three of his novels, four short story collections, and three non-fiction works were published posthumously. Many of his works are considered classics of American literature", "ernest@hotmail.com", "Ernest", "Hemingway", "+4886787877760", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-05 18:50:22", "Ybl Miklós tér 2-6", "1013","Budapest", "Hungary", "Portuguese writer and recipient of the 1998 Nobel Prize in Literature. His works, some of which can be seen as allegories, commonly present subversive perspectives on historic events, emphasizing the theopoetic human factor. In 2003 Harold Bloom described Saramago as the most gifted novelist alive in the world today and in 2010 said he considers Saramago to be a permanent part of the Western canon, while James Wood praises the distinctive tone to his fiction because he narrates his novels as if he were someone both wise and ignorant", "jose.sara@gmail.com", "José ", "Saramago", "+4756575650", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-06 18:50:22", " Via Stella 22", "41121"," Modena", "Italy", "Polish poet, prose writer, translator and diplomat. His World War II-era sequence The World is a collection of twenty naïve poems. Following the war, he served as Polish cultural attaché in Paris and Washington, D.C., then in 1951 defected to the West. His nonfiction book The Captive Mind (1953) became a classic of anti-Stalinism. From 1961 to 1998 he was a professor of Slavic Languages and Literatures at the University of California, Berkeley. He became a U.S. citizen in 1970.[3] In 1978 he was awarded the Neustadt International Prize for Literature, and in 1980 the Nobel Prize in Literature. In 1999 he was named a Puterbaugh Fellow.[4] After the fall of the Iron Curtain, he divided his time between Berkeley, California, and Kraków, Poland.", "czesiek@gmail.com", "Czesław ", "Miłosz ", "+4568585657760", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-07 18:50:22", "51 bis avenue Georges Clemenceau", "34000","Montpellier", "France", "American author. He won the 1962 Nobel Prize in Literature for his realistic and imaginative writings, combining as they do sympathetic humour and keen social perception. He has been called a giant of American letters, and many of his works are considered classics of Western literature.", "john.s@gmail.com", "John", "Steinbeck", "+56577858585", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-09 18:50:22", "Norra Kustbanegatan 15", " 416 64","Göteborg", "Sweden", "American writer and Nobel Prize laureate from Oxford, Mississippi. Faulkner wrote novels, short stories, a play, poetry, essays, and screenplays. He is primarily known for his novels and short stories set in the fictional Yoknapatawpha County, based on Lafayette County, Mississippi, where he spent most of his life.", "faulkner@hotmail.com", "William", "Faulkner", "+458568566686", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-10 18:50:22", "Av. de la Institución Libre de Enseñanza, 190 bis", "28037","Madrid", "Spain", "British organic chemist[1] and Nobel laureate recognised in 1947 for his research on plant dyestuffs (anthocyanins) and alkaloids. In 1947, he also received the Medal of Freedom with Silver Palm.", "robinson @gmail.com", "Robert", "Robinson ", "+363645747777", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-11 18:50:22", " Casemates Square", "GX11 1AA","Gibraltar", "Gibraltar", "Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize, the first person and only woman to win twice, the only person to win a Nobel Prize in two different sciences, and was part of the Curie family legacy of five Nobel Prizes. She was also the first woman to become a professor at the University of Paris, and in 1995 became the first woman to be entombed on her own merits in the Panthéon in Paris.", " m.curie99@gmail.com", "Marie", " Skłodowska Curie", "+356868959899", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-12 18:50:22", "Av. da Liberdade 127", "1269-038","Lisboa", "Portugal", "Franco-Luxembourgish physicist and inventor, and Nobel laureate in physics for his method of reproducing colours photographically based on the phenomenon of interference.", "lippmann@hotmail.com", "Gabriel", "Lippmann", "+48679958989", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-13 18:50:22", "Cl. 49a #55a-40", " ","Medellín", "Colombia", "German chemist. He received the Nobel Prize in Chemistry in 1909 for his work on catalysis, chemical equilibria and reaction velocities. Ostwald, Jacobus Henricus van 't Hoff, Walther Nernst, and Svante Arrhenius are usually credited with being the modern founders of the field of physical chemistry.", "ostwald@gmail.com", "Wilhelm", "Ostwald", "+879786766657", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-14 18:50:22", "Av. Javier Prado Este 1212", "15036","Distrito de San Isidro", "Peru", "Scottish chemist who discovered the noble gases and received the Nobel Prize in Chemistry in 1904 in recognition of his services in the discovery of the inert gaseous elements in air (along with his collaborator, John William Strutt, 3rd Baron Rayleigh, who received the Nobel Prize in Physics that same year for their discovery of argon). After the two men identified argon, Ramsay investigated other atmospheric gases. His work in isolating argon, helium, neon, krypton and xenon led to the development of a new section of the periodic table.", "w.ramsay99@hotmail.com", "William", "Ramsay", "+412442343244", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-15 18:50:22", "Av. Pres. Vargas 1261 - Centro", "20071-004","Rio de Janeiro", "Brazil", "New Zealand-born British physicist who came to be known as the father of nuclear physics.[3] Encyclopædia Britannica considers him to be the greatest experimentalist since Michael Faraday (1791–1867)", "rutherford99@hotmail.com", "Ernest", "Rutherford", "+14343232343", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-16 18:50:22", "Balcarce 460", "C1064AAJ CABA,","Buenos Aires", "Argentina", "French poet, journalist, and successful novelist with several best-sellers. Ironic and skeptical, he was considered in his day the ideal French man of letters. He was a member of the Académie française, and won the 1921 Nobel Prize in Literature in recognition of his brilliant literary achievements, characterized as they are by a nobility of style, a profound human sympathy, grace, and a true Gallic temperament", "anatole1@gmail.com", "Anatole", "France", "+8907967699", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-17 18:50:22", "35-37 Essex St E", "D02 Y891","Dublin", "Ireland", "Danish professor at the department of zoophysiology at the University of Copenhagen from 1916 to 1945.[3][4][5] He contributed a number of fundamental discoveries within several fields of physiology, and is famous for developing the Krogh Principle", "august22@gmail.com", "August", "Krogh", "+35353633466", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-18 18:50:22", "18-22 Greenside Ln", "EH1 3AA","Edinburgh", "United Kingdom", "Slovenian and Austrian chemist and physician from a mixed Slovene-German-speaking background. He won the Nobel Prize in Chemistry in 1923 for making important contributions to quantitative organic microanalysis, one of which was the improvement of the combustion train technique for elemental analysis", "fritz.p@hotmail.com", "Fritz", "Pregl", "+5886786787667", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-19 18:50:22", "Northfield Ave", "NN16 8TP","Kettering", "United Kingdom", "Polish novelist and the 1924 laureate of the Nobel Prize in Literature. His best-known work is the award-winning four-volume novel Chłopi (The Peasants)", "w.reymont@gmail.com", "Władysław ", "Reymont", "+53453536466", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-20 18:50:22", "66 The Cut", "SE1 8LZ","London", "United Kingdom", "German theoretical physicist and one of the key pioneers of quantum mechanics. He published his work in 1925 in a breakthrough paper. In the subsequent series of papers with Max Born and Pascual Jordan, during the same year, this matrix formulation of quantum mechanics was substantially elaborated. He is known for the Heisenberg uncertainty principle, which he published in 1927. Heisenberg was awarded the 1932 Nobel Prize in Physics for the creation of quantum mechanics", "werner.h@hotmail.com", "Werner", "Heisenberg", "+676786338699", "3");
INSERT INTO contact(deleted, duplicated, created, street, postcode, city, country, description, email, first_name, last_name, phone, user_id) VALUES ("0", "0", "2018-06-21 18:50:22", " Mokhovaya St 6", "119019","Moskva", "Russia", "French philosopher, playwright, novelist, political activist, biographer, and literary critic. He was one of the key figures in the philosophy of existentialism and phenomenology, and one of the leading figures in 20th-century French philosophy and Marxism", "sartre.jp@gmail.com", "Jean-Paul", "Sartre", "+69978977064", "3");